---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  maxHistory: 3
  interval: 10m0s
  suspend: false
  releaseName: traefik-forward-auth
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: 1.0.5
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    fullnameOverride: traefik-forward-auth
    replicaCount: 1
    image:
      repository: raspbernetes/traefik-forward-auth
      tag: v2.2.0
      pullPolicy: IfNotPresent
    logging:
      level: info
      format: text
    providers:
      google:
        enabled: true
#    podAnnotations:
#      secret.reloader.stakater.com/reload: cluster-secrets
    env:
    - name: TZ
      value: Asia/Riyadh
    - name: PROVIDERS_GOOGLE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: OAUTH_CLIENT_ID
    - name: PROVIDERS_GOOGLE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: OAUTH_CLIENT_SECRET
    - name: SECRET
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: OAUTH_SECRET
    - name: AUTH_HOST
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: AUTH_HOST
#    - name: URL_PATH
#      valueFrom:
#        secretKeyRef:
#          name: cluster-secrets
#          key: URL_PATH
    - name: COOKIE_DOMAIN
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: COOKIE_DOMAIN
    - name: DOMAIN
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: SECRET_DOMAIN
    - name: WHITELIST
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: WHITELIST
    serviceAccount:
      create: false
    livenessProbe:
      enabled: true
      tcpSocket:
        port: http
      periodSeconds: 20
    readinessProbe:
      enabled: true
      tcpSocket:
        port: http
      periodSeconds: 10
    service:
      type: ClusterIP
      port: 4181
    ingress:
      enabled: false
