---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  maxHistory: 3
  interval: 10m0s
  suspend: false
  releaseName: traefik-forward-auth
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    fullnameOverride: traefik-forward-auth
    replicaCount: 1
    image:
      repository: raspbernetes/traefik-forward-auth
      tag: v2.2.0
      pullPolicy: IfNotPresent
    logging:
      level: info
      format: text
    authHost: "auth.$SECRET_DOMAIN"
    restrictions:
      whitelist: "$WHITELIST"
    cookie:
      domain: "$SECRET_DOMAIN"
      secret: "$OAUTH_SECRET"
    
    providers:
      google:
        enabled: true
    # providers.google.clientId -- Client ID
        clientId: "$OAUTH_CLIENT_ID"
    # providers.google.clientSecret -- Client Secret
        clientSecret: "OAUTH_CLIENT_SECRET"
#    podAnnotations:
#      secret.reloader.stakater.com/reload: cluster-secrets
    env:
    - name: TZ
      value: Asia/Riyadh
    - name: DOMAIN
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: SECRET_DOMAIN
    serviceAccount:
      create: false
    service:
      type: ClusterIP
      port: 4181
    ingress:
      enabled: false

