---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nextcloud-data"
  labels:
    type: "local"
spec:
  storageClassName: "nextcloud-data"
  capacity:
    storage: "500Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/abdullah/ssd/k8s/nextcloud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "nextcloud-data"
spec:
  storageClassName: "nextcloud-data"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "500Gi"
