---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-video-pv
spec:
  storageClassName: media-video
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: x399
    path: /tank/video
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-video-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-video
  resources:
    requests:
      storage: 1Mi
