---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-documents-pv
spec:
  storageClassName: media-documents
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: x399
    path: /mnt/tank/documents
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-documents-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-documents
  resources:
    requests:
      storage: 1Mi
