---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-download-pv
spec:
  storageClassName: media-download
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: x399
    path: /tank/downloads
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-download-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-download
  resources:
    requests:
      storage: 1Mi
