---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "postgresql-data"
  labels:
    type: "local"
spec:
  storageClassName: "postgresql-data"
  capacity:
    storage: "15Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/abdullah/ssd/k8s/nextcloud-postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "postgresql-data"
spec:
  storageClassName: "postgresql-data"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "15Gi"
