---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm
      chart: nextcloud
      version: 2.6.5
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: "21.0.2"

    env:
      PHP_MEMORY_LIMIT: 256M

    persistence:
      enabled: true
    #  existingClaim: nextcloud-data
      type: hostPath
      hostPath: /home/abdullah/ssd/k8s/nextcloud
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
#        kubernetes.io/ingress.class: traefik
#        cert-manager.io/cluster-issuer: letsencrypt-production
#        external-dns/is-public: "true"
#        external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
#        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: networking-nextcloud@kubernetescrd

      tls:
        - hosts:
          - nextcloud.${SECRET_DOMAIN}

    resources:
      requests:
        cpu: "0.01"
        memory: "305M"
      limits:
        memory: "512M"

    nextcloud:
      host: nextcloud.${SECRET_DOMAIN}
      username: ${NEXTCLOUD_ADMIN_USER}
      password: ${NEXTCLOUD_ADMIN_PASSWORD}

      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array('${NETWORK_K8S_CLUSTER_CIDR}')
          );
    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgresql.media
      user: nextcloud
      password: ${NEXTCLOUD_POSTGRES_PASSWORD}
      database: nextcloud

    cronjob:
      enabled: true

    redis:
      enabled: true

    postgresql:
      enabled: true

      postgresqlUsername: nextcloud
      postgresqlPassword: ${NEXTCLOUD_POSTGRES_PASSWORD}
      postgresqlDatabase: nextcloud

      persistence:
        enabled: true
#        existingClaim: nextcloud-postgresql
        type: hostPath
        hostPath: /home/abdullah/ssd/k8s/nextcloud-postgresql
