apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: nzbget
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbget
      tag: v21.1
      pullPolicy: Always
    env:
      TZ: "Asia/Riyadh"
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      supplementalGroups:
      - 568
    ingress:
      main:
        enabled: true
        hosts:
        - host: nzbget.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: media-ssd
        subPath: nzbget
        accessMode: ReadWriteMany
      nzbget-downloads:
        enabled: true
        readOnly: false
        type: hostPath
        hostPath: /tank/downloads/nzbget
        mountPath: /downloads
        accessMode: ReadWriteMany
    resources:
      requests:
        memory: 500Mi
        cpu: 250m
      limits:
        memory: 4Gi
