---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "jackett-blackhole"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/abdullah/ssd/k8s/jackett"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "jackett-blackhole"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "20Gi"
