---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-video-pvc
  namespace: downloads
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-video
  resources:
    requests:
      storage: 1Mi
