---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: minio
  namespace: kasten-io
spec:
  locationSpec:
    type: ObjectStore
    objectStore:
      endpoint: "http://192.168.42.40:9000"
      name: k10
      objectStoreType: S3
      path: k10/ce93d7b1-2946-4cc2-afd5-1fa585eec33c/migration
      pathType: Directory
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: k10secret-minio
        namespace: kasten-io
  type: Location
