# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dKfpdx/XHVIfSFyX,iv:6nki5hgLq91VIQeAr7lPFs0SL/8kjSS4w2aYks0in0s=,tag:TRNdTxaiKzMfSrM6d8kUew==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:TQLzoCcqYX5JXx/jKf9QRrriE/QI,iv:tu6Gy5mWqJjd/vlm/Wewh4yUfRlvHahhUc83+apZfSQ=,tag:ABQDn7unFpcpsClhshZMkw==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:GoueF9dSxbUEFXdagofoJ3tn2iqmpAh5SuG7ws3aVWpD6RNBWZV8K+I5kloxSqqblLw4CYyp30llkoS3IYjZTUsYugGAUjBb,iv:FouIwCkM2I1hUhqiOCmNleSef38gIVZrIFMLcHk5cX0=,tag:67FFpn1tUGknjxUyC09SuA==,type:str]
    DEX_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Gxcy+Pw9fUurdEgmSmnHUdOGpaCZVi2atFA6qFAfAWWDYOdoa0SXmA==,iv:WzPZT15LJB3DwSCnSIe1YE7JYccdfo8K7s4ZJ1yNpcI=,tag:y30F4pHOEgdJKHYidN/oeg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:qZP2+YzeF/Adp2wGfvG22q8SZiSZhdXZ,iv:rGjmLJ+Xjk3+e/7XOdmuPWVhmg9iJQeCsCA1W7/IpLs=,tag:Sz5MjTf6lg0JTqy9ugZpmg==,type:str]
    DEX_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:VgjdeEryJ5onjiSawu53M816l18=,iv:/HwbFpj7dOrQXO2/7R0hLH0DPgJWYiKMlVPk3O7RQq0=,tag:nNbJ9ghxlBXukTTb4S8hLQ==,type:str]
    OAUTH_COOKIE_SECRET: ENC[AES256_GCM,data:+IzIHO37CHJd6xSQN4Ly1o5fwFGhW2w6UR6hAjP34NQGNm3+CvPsa6Lbnuh0Ddz91tcbkhgCQ9zrjhpo61VIXGgwuC6J6qqnXNCzmQPfqH+RsjQvHaUqmJryJdc=,iv:ycVKIaPScr/f48EFtn8r9wtfZFmHLXD5L98nzcDVi4Y=,tag:Rlqi504nVV/EbDVHkcgO/w==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:NLMYZ8Ja5cvBr+3I,iv:IuEKq13vrQicC9CrtnTJrtOsnbr9xeHV0TPCGiAhPJ0=,tag:jFEQKoHLjvbSD868q7vOng==,type:str]
    WHITELIST: ENC[AES256_GCM,data:SVH400bMwnXLjLmFzOj0dflgq2qFyLwEp4mxb5O9FaB+0bVY5rvMLZNP2R3sGHxWH4owonSaiR6KaDllfu7NXxAkrlYRJupkjkXw0A9kQKtWzcEA9gsAfuRE/jMh,iv:+sWAtke8dFHjDItW2KzpV4YXDpF1kiO8XExdzmL8puI=,tag:uQ2kePM6Jpw7jpEUaMT1FA==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:F0HS1IHsx01HsWc=,iv:QZCyqfnpiAwK2RyW/vyYYii3YpNTdzaLNZvmUq9zKxY=,tag:3yoztGSEPcUb01leyD9Q1g==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:bkCvK6dRx/ZZ,iv:nC91PqH5CoOCrve0vqLFrpP9B+lUY3OAy23p44kwBBM=,tag:Xkk/gwgT4z0AvAy1Qn1Wcg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:6CIYKujZVAg=,iv:Lc10qj+K7FAvsgCuS33cDob3eAXdAqRBdOwVahYAyVw=,tag:5a1ssT+Wh9TYLqA6MnzBuw==,type:str]
    AUTH_HOST: ENC[AES256_GCM,data:XjiFF82NTLO/xaY/fWd13m0=,iv:dSBT/25s9KkcRvpY3y8mdtoyObMOrZ+5WCfDtueU3Gk=,tag:+RtOVjIursAfbkOXdKcXzA==,type:str]
    CF_API_KEY: ENC[AES256_GCM,data:rPRcJQ10zGQIgNDW2DWI2npp6leTsb63vlxoXXpoxuRjplmSBA==,iv:tBuqKvUKenaPm91bH1/iHH2n4MQ/7seWAJh/7XoElRc=,tag:oS/qGVq+myNdadXUVzdNaA==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:bXqpnVikL08MtehK/Rp8U2yvUoWc,iv:wW6v39MAdcuw6ChT0SJlTMsennJeu+aaNppGekQHquc=,tag:gWI7GnxporAtqWdmZh+Y6Q==,type:str]
    LOCAL_LAN: ENC[AES256_GCM,data:RgXQRWmui/I2l1KmD38Q,iv:ev/GHWYM1S6iPDOpwZs4T5YiONVYi9yOzzotMjnibDM=,tag:H8FvjGyNzUYCMMtfp3DfCw==,type:str]
    SECRET_AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:LKoXH/pTlI92DqL9LqYy3kwtfvWTULeDeGy7sGRF/ziPLw==,iv:O2RcKpEeVpcfZRFkWbEJWEj4QAEnwdH+J3zeXmHZnlE=,tag:ZDHXqAyvEoTS4e/JD8EnyQ==,type:str]
    SECRET_AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:uKLhQKBcct1hYRaus+kfbqy+GNz4aJfliLgdt4W5Hhtqyg==,iv:G0A5kK9dDx8gquiPFSFxQjXwyuc5FiDauvQQ3KijOmU=,tag:uTXvxm6QNRmV5yeyQMyAVQ==,type:str]
    SECRET_AUTHELIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:FJ4fCNsc3QU+dTqOmMbT0oYqBHdmkq+D+UfYEaKzbDgIaA==,iv:a4Bv5mL0IBGoaTFpm0z9P2Gy2gEm9aKAeRExPB7wtAw=,tag:1Xe1lSScQ89MHvn0PQMDXA==,type:str]
    SECRET_AUTHELIA_SMTP_EMAIL: ENC[AES256_GCM,data:LJ7sWvJdHHYGzDiwGZlei78YwXMN,iv:zD9NeuRelX4A/k3d8P7r9LrLYY2Qto28gKT8JRTlCWU=,tag:QXs3NClqQERf5rhddM0olg==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:dhOqWssuYxxQJsUpHhgRyQ==,iv:v0rg2HTcT8932xsWmsCp0g76WSbJBhF1hDEuXbRshB4=,tag:yRkLM4jw723zWK3TXeCv0A==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:KJ+jGtJiLsnkIe+i+72lz2GGohOfAJTGn6V1hpF/zTRkjw==,iv:vEp0vb601Y3ilSOt2kXIzxD9DlSF7PKcGaiS6FIaVA0=,tag:0Xan/9b7K60uIO2byslQgw==,type:str]
    SECRET_AUTHELIA_USER_ABDULLAH_PASSWORD: ENC[AES256_GCM,data:HqIeuTAGDqM=,iv:NTf145Fd79CMace6ZhfmADW1m9FVGYd32O0wW/wszyw=,tag:/y9LWq1/gvYAkDin1Yp5SA==,type:str]
    SECRET_AUTHELIA_USER_ABDULLAH_EMAIL: ENC[AES256_GCM,data:EyqonRy21sSu2yDe985mKb+IwWFsEblJ534=,iv:jQA2dJ7FE20EbGab2WsDRNKknZVYAqfz61x7u9B+3og=,tag:3VIgE65SPBXs6G+e1If8og==,type:str]
    SECRET_AUTHELIA_USER_JEJE_PASSWORD: ENC[AES256_GCM,data:IggehXRhJ3j4,iv:VAtLqjse/NOgGDGQQcyuN/1Pp3m++FskvTMCUivUUw4=,tag:WiQ4IaQYh8Deyb9db86U3g==,type:str]
    SECRET_AUTHELIA_USER_JEJE_EMAIL: ENC[AES256_GCM,data:5yJoOjsl9/j+7Szsl4E+C7bXBQI=,iv:v4DStax3QpYy1H8UmYosm6ZH4sqIqSMjNF1KQcZAKZU=,tag:f47f80WXvIHPTGTaFTFbjw==,type:str]
    SECRET_AUTHELIA_USER_MALIK_PASSWORD: ENC[AES256_GCM,data:FpkHT4BIH2Tp,iv:exSl67VHGhV2aEuMwxHkYL7h+A+2XCty+rhlnL8UQuQ=,tag:YDt8jDzWY1dmDswkRa2tOA==,type:str]
    SECRET_AUTHELIA_USER_MALIK_EMAIL: ENC[AES256_GCM,data:TKsgsS2cHuosO0NstItYo5XGuBG+Wn0=,iv:bfvjFklNVaYzkNevRB9kELfTUY7c9WkrkQ37cBQKq+g=,tag:kAr9gpmGj0/JfYKEszPjIA==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:D1wEu1O5v56QNKzC/wH8Kljm31anjXB/dtA=,iv:ZlL6RMRVJ9lo0Ayiu/MxndyHGn6TM1FR3CAr3arbMKE=,tag:/guuZ0G63uo1ykICldprTA==,type:str]
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:nUfqaMVD/6udMrjQA4RZILRE+hulENZc9gnShBzPyMWTlQd7eZ2wLWcLRpjYj/f5Pu55wyNCU01Y3Hk=,iv:I/EHLCG3VhcLiYSrXGg/lT+h2FMp1UzUGkjxUOmHFIo=,tag:OWdyU77hVGLbxRsTIhD7Kg==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:ixGxUF+gnT8DmWUtiI8BfxKv,iv:2BOaITPZyxmieY/17o8xIk8QxdH0+h2yAqYlalwiRn8=,tag:LMxZCqASnDO/UVU+6mrnBA==,type:str]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:6EIrCjp3nHDpYY9l4gLfjV1m,iv:pnrnxP4WiBEYFXmq5IlWkGGYCYfgB85XxDAHK2HZ1cs=,tag:IuEcczlEdbIUmmil9IXNKQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:32tNMILwJzl+x4WC,iv:moP2/Vptq9JGIInw6bEeV5MTKuV64D0PKvuhA0vw1f4=,tag:YSAjyq8iBoxKeJF7C1DiYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T14:50:00Z"
    mac: ENC[AES256_GCM,data:4q9zaJX7PQDQTMrd2JICay40ZgREstgXL+StyPidI4woerYRl9sF8MRDH8MiB1pft/zk9acLSfwAHJUt9G1HtweSFSqn5pYe9zO2eoJFj8T5heqLXb8L6g6rgJUU4wE8D/ueCkA3YsQ1WyLw2Ml9Lyk7cQiQJ5LSRBg+33O4Ihc=,iv:HGLw3a2fAbtGu1VCr+FbBF5uD9WsvuCt/9JRrO0W1MU=,tag:fmlJCeH0RzXo4YEt7APH/A==,type:str]
    pgp:
        - created_at: "2021-06-23T14:49:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxqJrlfNLy7gAQ/9EYBtc5VA+ZGPS1iBDLlLWaWjM08j+taMveomta9WFJLy
            DQHIDZt/MeHiomHokHZAacnPOtmVjnoZCVtgIaq36aGNB67desqhvpJkkEOFPIeH
            lrZAjfYN0B817Tj5nfDNHGih7Df7SogHHrOoxSNeIEHzo9duQZq41H6Cje27Y+U9
            IBRcuBx9SpleGqegSpH7066GovD2vzR2wM0kPfnDMS3aeM+pFqXN5gpiYNDGa6gV
            baufzDE7HclbqVo0AZK5F1HwiSHDrtEKHV9jbSB2PFaYxbXyrltezzmX+Hm14HQf
            Rz5WD57D/3iXR6c8KbV8NbfzxxAb1uJ6wLZg8gyA7n7YlBiioSAr6RPcmIG+DpSY
            Yzhokn2GuGqqMnmQWL09fJtZel/00HJBWPN8hk9kfTvY+R24TjOnFNe6eXYZeVz1
            wKQWkG3W0AxB/l5qjtHE6gnLxHYf9DS6p3JCp9slxogLmlERZ2hAhm3P1+sedBGb
            se2WFVOqcVjk+lVj/KLte9f8LqNNO+AONVGA5NSQsH4V/vTQIBV/vhnkwQbw7wRe
            bjbiN8sPOO/1hUzhaHvlRYUg49R/g2wtbEahsIyXvI+fDBs6jCjxw0XTSZbXNiBf
            c+kGanZnY617nV8e+Rcb1W+gDItpH2+Z8L4FrFO895oh8vlDjEnaY5pk3Ge+REDU
            aAEJAhWS4RuhH0Tv0t6aS7NmMhuMAgkhx7hmc3pGfcfIEPlNoK7fp86O1wwea4ww
            2G/+2EyF+rXgJI+Ojt1Z4/kUBP9UYQ3+iaTnpsfHYAClz9QxxAXzbBf8oembcu2m
            BtLyGzhd/c/7
            =+Fex
            -----END PGP MESSAGE-----
          fp: D027B5C39D3572E0B05085C4EB83E8FDD60FE0A0
        - created_at: "2021-06-23T14:49:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzaFLgIs1yc4ARAAqmr+PYf1rN6hIiFVbkwaiEx8tHZni37Vi0NZyPGYlfpz
            my9OXLq5S52LI8DM6Eo29wGRLJEkP8uHwYkdSkkAcHcdcUWHeZM3EQAg04fM+vtn
            PMxQBSFIh8rLRDjcVMZa6Yla9tmz6RjxFsSqimcGld0wwXj7xGyNuaGgMbojGtyX
            lYAYrbxSmT1JfuasKO+TLjM+ofQsemPeaaG9XvDKD2YiqN8KZOWR06m5bbWIqJap
            xPaxOyhbP9jRE5h9zgl+uTLQHf+PTgBBYifxoWsYG3Ldp9AV0580fIOQkvbME5So
            Lab0perAes/NpKnKrMZlXgF1tsVI43KmoD63WmpXy+lTHNyUWPUq2Oc0M1f6OXUH
            yZq6lkypHo91lfvZb2awmc2pjSe0pERMtTjGQn5ACUmJtCZCpXi3Nx+EgfFzrOtG
            XqN/9NVQi+55aGigAOrAVswySziMeEnTtHcbmHvjlpW7Yl4pmr2AHYUZQEEp0Mc5
            esXIDLP3F2lh+C0/P9LMBptLMSRNNuJpQGZZZVwpT3mhjEIVIKhWlX53WOuMY7bC
            9bRSVUbq7AkV2QaDDRlaRE9JooFluaWLZD13qI9EokAP91A2+ilMdM7KInz44g15
            Q5oKGxqcigwg1WkCkKmrVjpVKtDD4t3m3h9LSKw9NSLeg2DgJPHpDW2TgduQacrU
            aAEJAhVuEwNawMwbsUdhy1lS7CyS75PVXsBeoJQOMpdXwCi5GkMwul86ql069pZs
            GURm8yH7yK12VzIeBb2hziwNcL5IRdo0RQ4RWu0FU0RffJDKYN2mVF2DgqlVxT+S
            KKsq+BrMs9Le
            =kVCu
            -----END PGP MESSAGE-----
          fp: 3EBA32A386091A562B0D00D8D0B0D01E85D514F0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
