# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:N1xkA8izKK8Y+Le6,iv:3ggK+KkMlkvBu5dS5N/ylKZ4pCLZF80Pcaik1VovCsE=,tag://xPLqiBlumdxUWshQjpAg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:AfjeU1nBNmqhnXWt0x3zOpvg8vTD,iv:gcalkUjOXSyc4hmvSKCGGsfwTvCmvlUeHMKL/6chBLM=,tag:tXRCpsMIgRLcyn14whyErQ==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:bq4BmX4U9IAeFaK2jwQQ/G8CZ0g+L5t34qW8uVvip+sBYtrXFQ7QR09nOw+ACDiYoTrZWqTIrw88tBrmX6Nak5xOTwFTOs+x,iv:LKE36KkHrl7/oeCbUyaOSXxlOw2cXf+lbIuSzGv69Cs=,tag:pZh/jMls7i3ri9xYSynNKw==,type:str]
    DEX_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:a5jDr23UYrhxzzSHOYeCO7Fd7PRjnVE5X6IsEcUWpOnqaYxUvBAWBQ==,iv:xoxEhYR1whp/Y5ujYdl4xvPQkum5UatqVjAnTUfgRcE=,tag:kfs2msj5tiv8vsxNaaM9iQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:KOFchpjqsu40IWeZys5UM1i9q+xMmvKA,iv:9sLMqpBue07/HVN4hUuM6elua5Qrj++o+/NlHAWPavg=,tag:o1tule3rZnxHjBu1bHemTA==,type:str]
    DEX_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:bzEZBMbHncNhRPAk9VJBgnRmtN8=,iv:isG3k43dPXH+k1t6hcueVIx/bQGXM37xdaL+956zn0A=,tag:iIcaj9/SGUBdWUAaErFwMA==,type:str]
    OAUTH_COOKIE_SECRET: ENC[AES256_GCM,data:WUuDP4lYH2yvdDFyl4IX46uGseOO1NMzJGBk6BUhacSzxR4roV7X34q9lracSdFKA8WZrUgpF5TQgqdVOhEc1rJb+RlbKRDdoscLeO/ssn990WuzlUOsIUiEbS8=,iv:g2uP89SgMr2j/cHBGe5O+Ptm6zrU3HkMgzdkve4R6EY=,tag:V/MYD9Z7xjM+J0zEeJ9+dQ==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:4VmlBVojKO9gRf2S,iv:qjR6Pho28PQQSaGDLXLoQmarlljOJWdbJJiXHYZ0y58=,tag:C5cv0rR8aG1/kWXCcBrC4g==,type:str]
    WHITELIST: ENC[AES256_GCM,data:DaZRI3BOCv1/rrzArvfRALTIEW7E8ci7Bqvio5lw5Wn5iksAr9glcBysVc6R3IyXJ5aECB4VPZaNP0OS1PVLbGARmfkPGj4btFwp/HRLtGlyoPZ4OXnckreyMtpO,iv:GTB6HhK9eICT8HrN+xTaNKntInZEtohSR/MtQ4AF5Dc=,tag:6N4hwaEiU2i2JT5mZQqTOg==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:pay1cfkfiSSzsco=,iv:iv1OqqJsmtrCexShJ42jK+JVR2m39RD1dJfzya4Reic=,tag:LC5feOKYR9b5TR1Kw1e2mA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:n96J0b3+sS3q,iv:MqwvWyNhX7tA9t1RMxir/xz8JVG2r+nSPOLppIxmReM=,tag:dUq84PDwcyAsey7DSP/MjA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:XRBQj0Ggd7M=,iv:cFh7Wt89GYaAXwKwurmFbiY2zsKQbnbj/vWET8vZP7Q=,tag:lLVkU3Nh1tnfgFnLzpDC6w==,type:str]
    AUTH_HOST: null
    CF_API_KEY: ENC[AES256_GCM,data:PAcicbaWv0GzvNVddw18cgYjl3vk1HNAUl8hHPrKr2/leFkyqw==,iv:7TxWJZz656hu7oToxKx8Hh3kJ1JrRKWQS3pLzERPpxo=,tag:URmiuwA7NLJWo9kvbJM2OA==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:aj3hGxV+iNXXRtSSMkiIWFpAWF/H,iv:JvlOn7ZAuxSYBcYNVDKZy8GWTbCmOoL5BSGnF1TNV2w=,tag:8oR75fXl9sxeAgKRb3q9xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-14T01:53:15Z"
    mac: ENC[AES256_GCM,data:9yryUp65Zx6iSpUwyciFh0qMNfsBWQxeLI8Zi1NsCjsnvcQStusUSTCRZLYBKYn+FscvFR+V/ezkkIUn0Pl79dStI2JM8Tp88OMWsGhChtUrdcn/WpuNvwd23YRADB3WcL8RBLb/RAPPERd2xMSE7eE49y/1jaSn9wdyOBLfbSE=,iv:5t1ncVqnxGHAFYo+y7DbDziciy1SEmAIbj0o0qR3z5s=,tag:smrYod8Af+78oe/F1aw9NQ==,type:str]
    pgp:
        - created_at: "2021-06-14T01:53:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxqJrlfNLy7gAQ/7B01FT/yyRyS2VyKmj1OTy0pWqF+b2KHH5D5zG1ckZOMN
            97U6QV4VZL2gjRwu2HoCHZflO15hgOiWaptuvkom6EulRoVQIedLhbxoMyNmWGuN
            vvkuICXIBqyh22/Dl6lYdcDzcqxjf1MLJjUgRjlDuF+uNKMPuvsFj5K1+DJE8f/8
            tHNdQ6OBnDP/P27j6WMiuYHE9mbL2pBRV+nDC0FQBfnmJopFb3b/KOz73jnld58d
            mJ69uEjIA7spo0sUJQVUM/y7vHeA2ESSUtCrC4XqcN4tqJqx9WXGRzxsJ5cdSzZ/
            iQMd52STlFbz6NMAXp7RH0ZiUVkypydhgg/XQeYHjBPWwx40kyYM8FaNDSchcOCh
            iZUFSUrqj0GPal+T+s16PCuRUP6d2ONYTqSpeEgQISP4kP+XUB4TiTKl9oObRGzj
            RLxapJdS/ImPDEG0lmOAYQ01vpxDH/bubqL0l35Cax7FMUC2+R47lsjJyNukxMFZ
            YnSCQeMCw5mg7ZAQ+vnLsJ6n/X8Dr6ZwPR6/5oJ58Y4JblcVvGH7MZcJ/ByxcFYU
            T/wbUx/66ixsIYuI6/dh/KoJAPZNJlmgLQX2J5Sqrnqjlbhle/ATrvaiC2ux4V5D
            +lFj+DIHAvE5C1rJM/BtzzEZrKPbFAYkEtdMc4uM+GsSqFm/dv8QT+WgHMvrFuzU
            aAEJAhV2okRdGaKd6/bTa9CJuZfAQuvYy/wpIdXT1RUvxNBSA5ai7ZQuGJeVoeX3
            nBASX1kG7ftzPXhQVWVPsVvsEoYWSjvuMCtoKnwjruwcoOklwO9XPTneJ7iYAI4Z
            mKOIToK+6+iA
            =/8le
            -----END PGP MESSAGE-----
          fp: D027B5C39D3572E0B05085C4EB83E8FDD60FE0A0
        - created_at: "2021-06-14T01:53:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzaFLgIs1yc4ARAAi6dT0V+thEiRE06kZnCRsnj3EjOmpfbPMaU9IKnMMoKG
            X44mExkdQsONuYPs3gF4BxAIvwN1/YD5vG4/FZ4bFo0sjzUwh0CFFJNoNAmp97cu
            S4HtTh35qWPfFgo5cc3+Q8tA6UxvGoR0TlLrH+dtC96hx/TVMGGIGGyCFRNaG04J
            AAFs/1w2NfJ5ov7Tvif5sM7hb2lLa90NhqLzlwth33TJkGUS5k/bV1FT6t8j442v
            z6spA6SakVoFDo+/urlV+0vuFvzbyarxh+W6woXDz2S6S+BzibZwSHzW5OQodhoe
            trtWQLJ7FIxUh4I6Q7EhjpX1ZMXbAp3uQXvbnDtDcy51qKC5qDJ+wS+CEvQJiBFD
            OOPBPfpvjLmezrRxr1kldGQkeZLsGdzLUaORQVtRaJaKptDO9As6F1M0M5EMlu1r
            2UQxf+xL4haVLC9wPZW/pd500+CvDBZa32C0fREh4WgSWDQhVgmqWF1qT0m0lg4Q
            f9Z8YOdD3msrzQ7E0tSgmZ771mrJvEBAa8AfVlfMyP87WoMpLGU9r/4hplUgvirG
            mmQsttRrVINHQJSP59dt77JXNsaRzfCAZl/obtTdhl5iJwKzKZwjuKQgaY+r2wIv
            rtWjTA6zVBnV5qK92gQKLSTcOKYXZGQXTa4YU/nzwc9cpAlEFJCi/O6YMZsl+9jU
            aAEJAhVKKEDA99tfsgGbTwDyo/mrIkrvLeTrLXlHu0uUvhJKboapZbpjL2S69G3E
            je1VJWwC2ymSoEz98jBjs8ImDRK44deFCxpNiCaU0Dktk2/y8tB0izNcX/DkcdEp
            yQVh0NXylMiU
            =czaf
            -----END PGP MESSAGE-----
          fp: 3EBA32A386091A562B0D00D8D0B0D01E85D514F0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
