# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:p701n1Upzp1pHUhz,iv:7r4sqseW8O2Duz3tRh+0CFgltVZrKGkXte5VPkEruts=,tag:iGiX24gj47aXmXl6aPdI4A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cf+JcgeJr/N0z4PkD0dKqVo1VZ/L,iv:qxQ2fWI8biAgN0g0ABuxbVxqhzUZJHshatYfLLdy9WA=,tag:9e98KVgA4hfxhcCPwfH0hA==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:MYgAkRwIsvj9vt/0Mtd5572tuwpR5Vl27X/GTSHCywzUlJlhXvDczyaXz4TLESkYQdc1A4ZUOxTOzw+B0m5Bb1cwIb8zomKy,iv:EflG3rrsGLeHniy6xFk7IoOX+O4Zlv+phPmQkaA7xYk=,tag:uXVoklWK3oZeK0hx+ii+5Q==,type:str]
    DEX_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:2GHSTV/Nzi3dQuZLtIuVoYZleENmdwqAgIxALMZOzlnS+sA964sx9A==,iv:zhfwFgNh+yhg61XrwqAiZIjdgsgH/YHh71at5kTO7v8=,tag:Ei397B2iQyGPXIv6Sw2uhw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Zj/LM+JzGPaBUm4riluOvF089ij/Gsrr,iv:Iyf4Xi0fvp5r3Da6UCQwcgwyHx+RHw9bI6a+rU1Ayug=,tag:drtBMbAec+eLgmxv/2j45g==,type:str]
    DEX_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:/mw/U+TR6T/erOCfVnc5lIs5/EE=,iv:8RmfRWQFQQP57WDPWFZwQc5HWYkPjGL4nbGudC5q4io=,tag:tUXfJh3gGwGxA3B/zxsyyA==,type:str]
    OAUTH_COOKIE_SECRET: ENC[AES256_GCM,data:6YUY8YLDvE8JMR1/tCrt+epCSyxJ3r+R4792X9IL0UgMkkB32MYeAh6KFVg+D3/EUOsdVxKEWUBqKTtx9CCGZRTMzmK6U2hdQENusJA3ZjZ5utUS0qAWltbkCuA=,iv:ly34hBbci42UrfDtJ5WfukgzarnFmXmDimvO/V4WtBc=,tag:toxTiQMYV7xPIsgTAKJMIg==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:InlNggvCxv9T+u9Z,iv:qEy2SmPUDHaF1XCpoZZQ4Mb3gddNoQs5UhxIYdB0OS8=,tag:oYgOC1sQ61Bl7hjs9BMGLg==,type:str]
    WHITELIST: ENC[AES256_GCM,data:PQoGTMcR5llR+S5eRJYeyPxKkoq4vw3+PxlliFOEA5BkR3BozUVaNlx4TeecAOMQwhgicr3mVRhvsi/lIfV4MSjKHEChuzrJipa4+l+VB8IXrTqq+mIufszOeyBF,iv:wr2vKrvdpoxzOl7A7JtQ+fdx9Yr9OfmlNRm+dN8Sb00=,tag:Cf8SkJz13d/tbKegkirQIg==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:n9JM3kNh9zQfWFQ=,iv:rR7njtQjR+Fim33ScmUL9fG6+5XKvXwLj+tp0kyCBEU=,tag:Db1AwXPm0LjyyFTmNpbgzw==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ZNER74dIBVta,iv:67/K/Qi/q9DkA+uOEePhqfOAH+VPYNurBgl+lXpQLzU=,tag:i44E+JjvvCFvsJCqRfsWrQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:MMldRgN0GK4=,iv:CbV1snhA7n6PWrVE5peUUlly6SIJxHAjdvXVY1HGiwE=,tag:TO/0k+IJLj9anBd9kPTvFA==,type:str]
    AUTH_HOST: ENC[AES256_GCM,data:SCGl3xfVNJv1ylSPi1Ze1+k=,iv:e97UEzRB8okRYcbkxNvSAtdwPiTusAUvXhl9CE8wBME=,tag:ZmLY9rRQbkqMJdEwrHKhUA==,type:str]
    CF_API_KEY: ENC[AES256_GCM,data:qKHRs7rQtMxOlHhQwMnJSkSJ462FZY7x/jj0UvQ3zr08NR+wzA==,iv:XLx6qJtSfT+NlF763NRcQEvSKHBXqdSXsePLobkuTJY=,tag:Z0Z3Il/UvzNO12EWzalSpg==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:jFwknm9fu+j2SZ6jSf47hkycGjkc,iv:7mxnICEz5h8L/bAYsFZSajTjIZw2bupuwpbF/r/NO30=,tag:ZGE6GXjZAlrr2lU7nNYEfA==,type:str]
    LOCAL_LAN: ENC[AES256_GCM,data:4Ova56Gyk5mXrgH9X/3n,iv:NJF1ixRbYrdKQfw+MdpaJ2FDuoDbo9K2PnzQO7MgPqs=,tag:0cY0FqAT++dBJxsmZzie3Q==,type:str]
    SECRET_AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:uLDgNeT+pVDGRx9CZeJbRo/Vq7pwHs1I1Z+XxwHapLm+Yw==,iv:/P6Ch6g0LLQVtsO2SA54IYklM0uH/vXPdmv2wyCe+Hc=,tag:AIhsijuRzzBuVYx9SEp9RQ==,type:str]
    SECRET_AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:fcS5paL2HjQOzHt9WYeUvBXkUnBXV9XwRXKEsWrEN/2XxA==,iv:u/psViYRvTzIgvAuaM9IOxoTknc9wzaEgY5vSmibVj4=,tag:u2SNqw9CAwkwfEkZOL7Ghw==,type:str]
    SECRET_AUTHELIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:b6LliUODQN7/lN6HsXiwp4DHhg+0I70LhHTfX+EbZulN7A==,iv:f/ia32tvxc5FPiJJzLSShkqQ4S6wsQfr0DMrZeIUXh0=,tag:o95x6vCDm8DG9gLAuoxshw==,type:str]
    SECRET_AUTHELIA_SMTP_EMAIL: ENC[AES256_GCM,data:Z1v0G8kIqLmWb9WHNq1gbrmlmFA7,iv:CfpxE4Nfsnhob6eqmh0bAp5YM8s+fNcpjVBoDlPE6BY=,tag:CZnd9jXm9Fqn/JGRE7aauw==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:svDnDMPvQHpW/a1CSG5M9A==,iv:XuPy/OzT0arNz1zRFDqdi4ePEBNvzBgm/GaQeHyOXf4=,tag:gW2hhNJksdOBQSX9vWOa+A==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:5xmkmDOmtgTMUtc02sI5W/uDvdgbkbhCHi3zDbqWLderAg==,iv:8dtmyVeLy9Spk1AVpIciAmOLeMy4vjrJwWm3NTTE6sQ=,tag:tmakgoLCaSGM5EnmG2zTLQ==,type:str]
    SECRET_AUTHELIA_USER_ABDULLAH_PASSWORD: ENC[AES256_GCM,data:5Ueskmk63F8=,iv:Ea8E0oezRfgs+NKd3+lk8OPau+nTbV4rA0rhmqAeP/8=,tag:spV8P2FbvL92P8cViZmu2g==,type:str]
    SECRET_AUTHELIA_USER_ABDULLAH_EMAIL: ENC[AES256_GCM,data:fyrdx2mm573/C0/UuMUluwRc2MRbGU1D0B0=,iv:xVLxE2Zrofu9h4/5IE5bK4UqkIaEUb1SBXSyQJCLU3c=,tag:6JvJ16OhLl5NdR/zI5lZMg==,type:str]
    SECRET_AUTHELIA_USER_JEJE_PASSWORD: ENC[AES256_GCM,data:E9YhBic3dby7,iv:+UtK9ib7XEUaRYAxqupwHV8gLpqSEC/29j6zyVeqKPE=,tag:1D+7s8GceOmwHXSRH3Ch4w==,type:str]
    SECRET_AUTHELIA_USER_JEJE_EMAIL: ENC[AES256_GCM,data:mpRhD8okOIvT3xcRxJ7fjFwFEB0=,iv:kDbcxZMvUea/XHFyMT1zL+DFzbVvD1U0Mqngx1OaLec=,tag:UsHEOhJNDJRukhHiMyX9Xw==,type:str]
    SECRET_AUTHELIA_USER_MALIK_PASSWORD: ENC[AES256_GCM,data:3kw2ppHJF2nt,iv:ymlsH50g4xcipicHjQs3jgguX44ZP89/APh4RJoIbmQ=,tag:dNgC/FlhnQRq6QcMrQPl6g==,type:str]
    SECRET_AUTHELIA_USER_MALIK_EMAIL: ENC[AES256_GCM,data:Gce9QuTd2HT/9SOxDvhhP5LmCo94M1s=,iv:uHIXoOLO9d4JsF6lLoKPd1Iu1+X4eU2MzcGILYpVXjg=,tag:juQyhw0bI3gVMugeQ68gvQ==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:PZCF9MS4o1RZO5WlKmgh4ygHke2DAkMkrdU=,iv:Sa98N+eVaJGUq3evcVihwOh2Gkz2M59AiJOWwWzdl1E=,tag:mb4n0WHGsjfowSHe9u7llg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-16T13:14:03Z"
    mac: ENC[AES256_GCM,data:8yuYZ7Drv1QWY5B9Hw18ZEB7DjhzaBNRCCX+9oGpiHRkVkxYz7pgHwstuhp9TwLRPYK2RtmjgaEJ4G6/9wrV6VACaQCgfBY7ZdFy07E8SfRCkFHsrshxVKhnnZb0hSAksssAsgMS6HsT0gERjdREfrL3gR8ImYOgRSMIIi2qErU=,iv:EqoNJlmX+U6CdFmqTnTw+hEQPvhOQMlGZRQ/88Ac10k=,tag:upk4jKd4xf1/KJcbh4OA8w==,type:str]
    pgp:
        - created_at: "2021-06-16T13:14:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxqJrlfNLy7gARAAlSR0xVBLfOs2Yy4SEXJL8upAC13eSLfjS7R80IpBBaDY
            kCwMCGSlQAQmoXUsYX9HxHHV5qasPnTYeUaMaps5ZHEKCWeEBJrFg5GyupREohQW
            P3Zs+pRv9BrXyLILjw1bubeDIMe9UAmlT+beFlsAgzZv1Gyofc0hpUGXJpimXP9/
            SjKnJ8IpWXyKwCVF7mHFvCYOHt9pTmAXtqAcaliZ7IYNHYp4kBqtbwnBBK4Z3fTr
            dtWQsPZz88LAjH5ftdn0alBcLl7b+zKlZkgdo5x3ZvCZnBFBunt/RHfheZFVEtFa
            uPSGezMUNBoG4WfjxiDDhEX225ca6uBIPholMmFVn8kyIArPx+mAeHgdv63kMBGu
            kudnevm+OeWdheqkM9TTTTUgTu2b/rGTaJqe3fU4O9SPJOoRYqDFV3P1ImjtTIr1
            VQ0gCM0/SV5iwsaYSrkMsIZ+HadYrE22H4SraI61MpBe9Mkeog719tkskIMNL8tv
            B+fY6o6TU6qVj220UUaD/b5JydJwAL7qpwM7vZyTfn9bkVt/fMJlYXFrl23FLb7k
            grLJNviTVbo3PKyohi9WIxSeiDCwkEdTKqUF9A1YFBy+1lB0nsj3xzHzevflCm0w
            /qm4On4C2myuIVeHfltmvP7dJ4gQ5/HN/fW+80lbHxL6NXWarhA5dpwjd59kQs7U
            aAEJAhVOHfYhW4ZorEt99wpymnV+3OVV+V38p3swZg76Oiuv25JO1J6XKSsR78LY
            FdPJYsh8sIZy2UDAixOWeFpDKP+mgLL8goNLg5ip0fuwo/cu4GFHXqDFZgy7ny3y
            Yj8uQBMres6N
            =nyLu
            -----END PGP MESSAGE-----
          fp: D027B5C39D3572E0B05085C4EB83E8FDD60FE0A0
        - created_at: "2021-06-16T13:14:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzaFLgIs1yc4ARAAnqHjL9jnfYPKrgdl9ptT6teeWQwRHPbLc4XVgHETYHtc
            bXF9PGbInF2PZLY7cJWkftd2GWdNLD4hCL4KW53kU+sHwEqAtvjoL2QAUNv3vtik
            DhqDx8Hy7RLJj7kdMTeSoBEHbGqKn+dahW+i43GfCBp+vQsuHeICAgA5I6ka8bs/
            dIpStpNpj6MYf8nL4qWfXw8wMXKbxrpimDQfQ5dRTiYje3sIMAemZECwJSOB8oRT
            AG/N1jW+ZgAu9At6DaVsxXYz4qQ9JHRZR4QxEySgbiDUGH4ZZimAhj8m/vCE7Qyy
            lMMva/W031YsQ2XDujJKepEyex6YG/j/T6mUkwLMNJOJEBonvjTx/woVrsMUcAqE
            lpaLEXLu36cTc1QZ6xiGSP3JhYUgX0pFpPC/KYohTUqTKdjrz5tj/cOVSaBUfK16
            yALlNqhWL8WQgJcvanHBPhWighzUueXochFPvPDaWlbveHsy2XCRCgTL35oqZfrC
            wQ0U2kbG3SzZHoOZ1c6JZ3hQwH1g27ELgNYSUQjPKYDswqRLOn2akGSzHIOCr7Mn
            +Xqa6/D8rrAxqT4tB1+02rkyqtiU7+Dej4ii/rtjhS/GyZ3o5v6zkf7hlhh5/MSt
            7/cmwGKmon7TaJuTLO0qeFBiPEvDneZt7q1lrpLrNW/5Wxl0by/nIMPmFj6+zanU
            aAEJAhW0tAzHC9uIw9pFxe149RAi7eBJQTr1jt6AIfouGSPhDvZUGMoe1cqUknnD
            Wcxu7KUcgaiWl5rbbDx1iIw0hJjU4EiD/7q4HR5flJ6QvDV9d2NHyVV9pG0Tf2oM
            uOSVYcvrUu0W
            =5P0l
            -----END PGP MESSAGE-----
          fp: 3EBA32A386091A562B0D00D8D0B0D01E85D514F0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
