---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.10.200-192.168.10.240
  INGRESS_NGINX_LB: 192.168.10.200
  SVC_TRAEFIK_ADDRESS: 192.168.10.200
