---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
spec:
  interval: 5m
  chart:
    spec:
      chart: transmission-openvpn
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: geek-charts
        namespace: flux-system
  values:
    image:
    repository: "haugene/transmission-openvpn"
    tag: "latest" # Suffixed by -armhf to pull the ARM image
    pullPolicy: "IfNotPresent"
 
  env:
    - name: OPENVPN_PROVIDER
      value: "SLICKVPN" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
    - name: OPENVPN_CONFIG
      value: "Netherlands"
    - name: OPENVPN_USERNAME
      value: ${OPENVPN_USERNAME}
#      valueFrom: # Reference to the secret | openvpn.username
#        secretKeyRef:
#          name: "openvpn"
#          key: "username"
    - name: OPENVPN_PASSWORD
      value: ${OPENVPN_PASSWORD}
#      valueFrom: # Reference to the secret | openvpn.password
#        secretKeyRef:
#          name: "openvpn"
#          key: "password"
    - name: LOCAL_NETWORK
      value: "192.168.10.0/24"
    - name: TRANSMISSION_PEER_PORT
      value: "47444"
    - name: TRANSMISSION_DOWNLOAD_DIR
      value: "/downloads/transmission"
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
  service:
    type: ClusterIP
    port: 80
volumes:
  - name: "media-ssd"
    persistentVolumeClaim:
      claimName: "media-ssd" # PersistentVolumeClaim created earlier
  - name: "dev-tun" # Needed for VPN
    hostPath:
      path: "/dev/net/tun"

  volumeMounts:
    - name: "media-ssd"
      mountPath: "/data"
      subPath: "configs/transmission-data" # Path /mnt/ssd/media/configs/transmission-data where transmission writes the configuration
    - name: "media-ssd"
      mountPath: "/downloads/transmission"
      subPath: "downloads/transmission" # Path /mnt/ssd/media/downloads/transmission where transmission downloads Torrents
    - name: "dev-tun"
      mountPath: "/dev/net/tun" # Needed for VPN
  securityContext:
    capabilities: # Needed for VPN
      add:
        - NET_ADMIN
