---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  dependsOn:
  - name: vpn-gateway
    namespace: vpn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.5
      pullPolicy: Always

    hostname: qbittorrent

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
#      runAsUser: 1000
#      runAsGroup: 1000
#      fsGroup: 1000
      supplementalGroups:
      - 65539
      - 1000
    settings:
      automaticPortSetup: true

    env:
      TZ: "Asia/Riyadh"
      UMASK: "022"
#    service:
#      bittorrent:
#        enabled: true
#        type: ClusterIP
#        ports:
#          bittorrent:
#            enabled: true
#            port: 18289
#            protocol: TCP
#            targetPort: 18289

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
#        type: hostPath
#        hostPath: /home/abdullah/ssd/k8s/qbittorrent
#        mountPath: /config
#        accessMode: ReadWriteOnce
#        existingClaim: media-ssd

      media:
        enabled: true
        existingClaim: nfs-nas-media
        mountPath: /data/nas-media

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
#          cert-manager.io/cluster-issuer: letsencrypt-production
#          external-dns.alpha.kubernetes.io/target: ingress.${DOMAIN_1}
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
#          traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918@kubernetescrd
        hosts:
        - host: qbittorrent.${SECRET_DOMAIN}
          paths:
          - path: /
        tls:
#        - secretName: tls.qbittorrent
        - hosts:
          - qbittorrent.${SECRET_DOMAIN}

    resources:
      requests:
        cpu: "0.3"
        memory: "1000Mi"
      limits:
        memory: "4000Mi"
