---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nas-media
spec:
  storageClassName: downloads-nas-media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: x399
    path: /mnt/tank/video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nas-media
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: downloads-nas-media
  resources:
    requests:
      storage: 1Mi