---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: media
  namespace: kasten-io
spec:
  frequency: "@daily"
  retention:
    daily: 14
    weekly: 0
    monthly: 0
    yearly: 0
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - media
  actions:
  - action: backup
    backupParameters:
      filters:
        includeResources:
        - resource: persistentvolumeclaims
        excludeResources:
        - name: nfs-media-rocinante-pvc
          resource: persistentvolumeclaims
        - name: nfs-frigate-rocinante-pvc
          resource: persistentvolumeclaims
  - action: export
    exportParameters:
      frequency: "@daily"
      profile:
        name: minio
        namespace: kasten-io
      exportData:
        enabled: true
    retention:
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
