# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kured-discord-secret
    namespace: kube-system
stringData:
    webhook: ENC[AES256_GCM,data:qnF92aKgjHzzkX2ebCg2t+xZyqmpIGsxW9woFHpI/zArgcV+V8dsV7mMQwI7f1DDB1BF6ISlKuEciPgqdUISuGt4FoHx3D8jxaUziWhys/SJZ6dHxs8VUJdHjl0vHHlW+g==,iv:XODJKbzxBtCftM2JwJpZiOC0XKls26er83m9rA30BCA=,tag:wz4a2TwmBkXp0mnJueYPtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T23:47:16Z"
    mac: ENC[AES256_GCM,data:7/qt/pjq+WWpKrp11b5xiS6LxI3jb4ENGJeSnhyRgUSh7gRqzsFrmT8oNGEgdoXSLQEirjLf5YOJDYpvlHjyym+E5pLDTNs/aizspOLMy/GcF8EPWaYJGmkqiNloFBkeD+5dm9BNFBb/ZJ/7F0MSGGVyfMvZIpJQZkF6Tqtcoeo=,iv:3r6ltS43ClacV+utKGoMYi1dmyG3Ut4ecfautbxvGkM=,tag:4uXCU7JmD8B8c6oJrCYMmg==,type:str]
    pgp:
        - created_at: "2021-06-23T23:47:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxqJrlfNLy7gAQ//RYUSdwp3gwjjLusN8oNdzBMqT2CD2Qn5O+evN4AB6UNn
            EDDuJ9p9+l3wkg9Qo0UyNz4Set04dkuTWPI7HuRbc/q40G+farTWihQ0sTHSrMk4
            qAUC6xBvXP2e3/MSAEekD2phuQm6QC7gQA4w3XB2fmLX6s5WlVEv6LNAtameEobU
            r9uk9yabdj911wwU/cJ7I2/4tQ8j09Ow0NK2Xa0fowqbFTqNwOlffJhEQQfR+rlO
            Jcatye2qklPxJzmEUc1fAutW2T2GPc9H98r0g6kLIibiLlnNk9XE6t5Uz0IOMCiw
            rhDH3UNxlLi5ZB8sM8SgE0AM7BG89OdOMCk3mIP3LdAy82PEUubZJ2fruV65bDkP
            3WEmwBi0lA9zSw/yf9W7hEGZXiSLKbvAFn8VYlMxUnB+LAQbYUYA31b46yYdNe1u
            NCFljbDVQcuGiSuiaRXbrcfmssUkJ/dk4MYcGDV/mQRibAzq1BqzwQseU2vi55P7
            tzR+E9sjJ9v24Uf2X0tO4Yv3f6n4tNAru/supWTL+8+dKAEpqEdXDPVOTJlG1FQu
            PW4dcQqPLZZWV4751P/JHh4Db8TfXazHUTpalXXczFwNyQnOHzou/p1c7M+g0qst
            ZTtzC2+unlMvtkPwvO3hi0QcjnlGWKZNicQIulwKboSqWelxgjhho3N3hVVdMWbU
            aAEJAhUnyFfCwsw45YYgR04a/TByCoJFQKpPc0+MsUussnda8AVzigrTEH0RIqLk
            O9FaS0gx5Q/F6EBLMD0hT1exjxtoQUAxr7wn+WwpoVGdtSC8zoI4gFbUkxubn+yS
            H0+Ijg466MAZ
            =ULqb
            -----END PGP MESSAGE-----
          fp: D027B5C39D3572E0B05085C4EB83E8FDD60FE0A0
        - created_at: "2021-06-23T23:47:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzaFLgIs1yc4ARAAw2ZnVrUe7qgC5tN2cuTQS2+hPFagRf5gkzMD+kPBGycI
            evYGAVk57JEHZtNcDL5GkmLu+Kf01B0iXS6BmJUBJx9ptwYg4blz2g8iU3nJEeFE
            I8pWkf9eidmfYy55ZFGjjDGQccJdAXIbwQRcgsqfxg+DY+oVx/FlWWtBkOQaDKvp
            T5X4hof8w8Jd81bSdcL/pSsxRRjVsEKHyGRVCkfGuf0bRv0hqGZbUB8CfrmsrC+b
            56tzynNYr78PN+DMkyU/pMsQ1X42nZh2QM1rVJ0J/BAZAqhAchV8oIumnqeKecsI
            0gyig3upgG3DG9I54L5VskKllWA+hX+jbm6ZC+PE4/XDk3JjUlyEp2PvsVgMb03W
            +0QJbmVW04byjDaU2fQT1RBtzlqWEVUXdqnu9tklS2bq6a8Du1oPcfPkzX1TrKLX
            f/qxf8hwgaZwazA6ThBoSm2Emxh2wGNsJhO7uIZijEYT2QGoJ7MLZfoIlVRhdSbi
            MAKYHDobB6RFRKxyrcHQcpDJN1cawtpIkBoINQzkAxsStuG3oosh3BIEYh/8IeVn
            qmZDwTASMH2GULseJHZreplLM7SmHbVzLbE1TJCEY/7nVaubpWVWoR8IMML/HGhX
            6Zcb8CmeFbIwqnQFDAVbNep+0vUGaB06JcsSPFnwjnqpgfVF5nLclCr/po2nIqXU
            aAEJAhVkAFZsMaFqkOBbFQq5K2qPd80g5lxhCzrtzbqiXLT2z/TE/fERDqyA6PK8
            Z0L3fVwBcLp/BN6kHVXEdR/S8fW7BUyxwBpd1x2ZmPKNZLlDjItfiaRZPW/aOUnf
            GMfp/M1aqEAx
            =4Lsq
            -----END PGP MESSAGE-----
          fp: 3EBA32A386091A562B0D00D8D0B0D01E85D514F0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
