apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- _pvc
- sonarr
- media-ingress.yaml
- radarr
- nzbget
- nzbhydra
#- transmission
- overseerr
- plex
#- prowlarr
- nextcloud
#- jackett
